---

- name: Install the PowerDNS Authoritative Server
  pkgng:
    name: "{{ pdns_package_name }}"
    state: present

- name: Install the PowerDNS Authoritative Server debug symbols
  debug:
    msg: Feature not supported on FreeBSD
  when: not pdns_install_debug_symbols_package

- name: Install the PowerDNS Authoritative Server backends
  debug:
    msg: Feature not supported on FreeBSD
  when: not pdns_backends_packages 
